---
title: "Lab Report"
author: "Awais Ansari & Dominic Nieder"
format:
  pdf:
    toc: true
    number-sections: true
  html:
    theme: darkly
    toc: true
    toc-location: left
    number-sections: true
bibliography: ../report/literature.bib
---


## Research topic

Our experiment contains topics on

- laser physics: external-cavity diode-laser (ECDL)
- atomic physics: $^{87}\text{Rn}(I=3/2)$
- optics: alignment and optical components
    - linear polarizer
    - quarter wave plate
    - half wave plate
    - lense
    - Fabry-Pérot interferometer
- spectroscopy techniques: Absorption, Flourescence, and Saturation
    - \dots
- spectroscopy: Fabry-Pérot interferometer


### On finding a topic

We find it difficult to pin my interest onto one specific topic. We would like to set up an experiment capable to observe the atomic structure, i.e. to see the fine structure– or hyperfine structure splitting. To set up an experiment that is capable of measuring these incredibly detailed measurements physical structures we need to focus on the tools that we use to analyse the atomic structure of Rubidium.

In our opinion, to make the extremely detailed measurement of a atomic structure, a detailed understanding of the external-cavity diode-laser (ECDL) and its emission spectrum. Detailed knowledge on the diode laser should provide us with the means to setup a ideal frequency to observe the fine–, hyperfine structure. But how do we characterize the light of the ECDL? 

This brings us to the issue on spectroscopy. The Fabry-Pérot interferometer only measures relative spectra – though very precisely. To correctly characterize the emitted light of the ECDL, it seems advantageous to gain a deep understanding and a characterization of the Fabry-Pérot interferometer, which allows for the full characterization of the diode laser. The characterization of the ECDL go hand-in-hand with the characterization of the Fabry-Pérot interferometer.

The last point to be considered is optics. Not all optical components need to be understood in great detail to characterize the ECDL, though some shall be essential, i.e. a lense as well as the diffraction grating on a mirror are an integral part of the ECDL.

The set goal should be to **fully characterize the ECDL**, which by necessity shall include the characterization of other parts to the setup of the experimental set up to EIT.
This means, we want to:

- compare emission spectrum of ECDL with theoretical prediction of semiconductor physics:
  - How does the population inversion take place?
  - What is our semi conductor made of (i.e. GaAs)?
  - Is a characterization of the semi-conductor possible ($I–U$)?
  - What instruments do we have to measure the spectrum?
  - What is the Free spectral range of the ECDL (Fabry-Pérot modes)?
  - Temperature dependance of emitted spectrum?
  - Can we determine the diffraction index $n$ of the depletion region (optical fiber)


As concrete next steps, we need to find out about material compositions and the dimensions of the diode to then understand the models that describe the emission spectrum to make numerical predictions.


## Dominic: Literature collection

{{< include dominic.qmd >}}


## Awais: Literature collection

{{< include awais.qmd >}}

## Set goal: 27th - 30th

We want to characterize our laser diode. 
For this we have 

1) the simplest setup to start with characterization is have a laser diode, isolator and powermeter (photodetector), and vary parameters; temperature, and scan through different diode current and observe change in output power(luminocity).
2) set up the FPI to measure the free spectral range of the ECDL 
3) measurement of the beam cross section

**On 1)**
We face the problem:

- the voltage across the piezo actuator fluctuates and drifts
- the data shows a drift in threshold current $I_{thr}$

How to proceed:

- through power meter (photo detector) optimize piezo actuator voltage i.e. $P_{dtc}$ is maximal and 
- scan through piezo voltage $V_{pz}$ for $I_{pd}\approx I_{thr}$: to obtain understanding of potential drift and fluctuations
- set $V_{pz}$ to maximal feedback, i.e. 
- proceed with $P$-$I$-$T$ characterization

**ON 2)**
We face the problem:

- 

 from the data extracted through these observation, we aim to 

## Glossary

{{< include sections/glossary.qmd >}}

## References