## Introduction

Goal of the two weeks period was shifted from usual goals of being performative in experiments to learning the process of scientific research, (which not only includes progress and decisive steps but also consensus over steps and mutual understanding of progress), hence whole activity was focused on learning research process and we used topic of ECDL as more of direction for our two weeks.

- The task that we were given was to assign ourself a task and observe ourselves and find issues that we had in the process to achieving our goal.
- The goal we assigned ourselves was to try to understand a cavity diode laser and simulate a simple model of it.
- Aim was to keep track of how we progress and how do we live through the differences and process of coming to consencus. This will lead us to find a way to level our understanding and bridge gaps we both have and how to check if we both mean the same thing when we are talking about any scientific term or process.

## First Week Status

### Finding Literature

During our first week, first task we faced was finding literature that is relevant to what we wanted to achieve. So we both decided to read different literature, and our initial plan was to later discuss what we have read and bridge knowledge gaps between us two and come to a decision about how to proceed forward.

### Difficulties

- Knowing what literature to consume is something "A" struggled with. Searching for literature over internet is tricky, as much as we have a lot of information, but its also easy to deviate from topic each time we try to dive into a search.

- Feeling of not being able to completely be confident in knowledge was always there.

- After reading different literature we still had issues communicating the information and bridging the gap to come to a consensus about our next step, which lead us to consume time.

- After going through literature I thought of working on simulation (I used AI), and after getting done with it, I realised that it does give us insight but it is half insight in a manner that we don't know if it does represent our system, or how much does it deviate from our system; hence, we need to take data from our experimental setup.

### Decision to Perform Measurements

After having discussion we came to agreement over the fact that we need to setup experimental setup and perform some measurements.

### Experimental Attempt

- As we started to set experiment and take measurement for P-I graph, while taking measurement we observed fluctuation and drifting of peizo voltage, and hence change in the output data which wouldnt suggest any observable pattern of behaviour. As more than one parameter were influencing the output parameter.
- During this we had discussion and we decided to first find mode hop free region which according to our logic should give us good value of peizo voltage which has max mode hop free region and we decided to first find that to have measurement for PI graph.
- Thing we missed out on is that peizo being parameter that change the length of cavity if it drifts then the centeral mode also changes hence changing the output information.(what we didnt discuss much was what if we turn peizo voltage, as it would have eliminated problem of drifting and fluctuation of it, but when we discussed this possibility my argument against it was that we wouldnt be in hopfree region hence the dataset wouldnt be translateable for optimal peizo value.)
- This discussion became halt point for our progression of trying to collect data from the experimental setup, as we realized we had different ideas of how we wanted to proceed in our rest of days.
- We pondered upon more of philosophical question of how to find agreement, and how to know we have equal understanding.

### Second Week Direction

Try to have numerical model of these parameter and play around with the inputs and observe dynamics of output and understand the behaviour, and in mean while take data of inputs from real experimental setup and observe if our understanding of dynamics make sense or not, and what
pieces of puzzle are we missing.

## Issues

- one of core issue I can pinpoint is finding structure to our progress in the time of crises.(In the time when we don't set anything as definite truth, all statements are equal truths)

- The most valuable skill one can ever learn is ability to figure it out

- how to communicate the thought in the best possible way, so that we can make sure our information is transferred at best, without deviation.

## Consensus in Scientific work

Consensus on Wikipedia is defined as a general agreement, accord, or harmony in opinion or attitude among a group.

Consensus itself is one of the intrinsic features in scientific work; during our two weeks of EIT experiment, we spent time pondering that question of consensus and also about how to agree when we are not dictated to by right or wrong by a supervisor (because in this two-week period we were given total freedom, which means there were no expectations to hold up either. This reminds me of a statement by Kafka: 'I am free, and that is why I am lost.' Which was how we felt for most of two weeks.

We both agreed that in order to make scientific progress, one needs a system of active input and a feedback loop. (We defined progress as active agreement between person "A" and "D", not progress in a performative sense.)

**(We need to define our system of active input and a feedback loop)**: This system is kind of underlying; without actively working on it, **input** is we first try to define (one needs to explain what it means to say we define something) one thing as we understand it, and the person starts to ask questions around their doubts about how we have defined the thing. Which I consider **feedback**.

This is more of a reflection on our two weeks and suggestions on how this could have been better and could be followed for our future endeavours.

## Question

- Personally, "A" finds it difficult to structure my project when I cannot see it as a whole (here "whole" means where to start and how to learn in a constructive way without spending a lot of time finding the right way). Which begs the question: how can we focus on making better progress under constraints when we have less time, more resources, and the potential to deviate?

- Differences at work are not only scientific but also aesthetic in nature, and occasionally scientific conflicts are not entirely about right or wrong, but rather about differences in perspective. How can it be addressed?(In discussions at times we realized that we disagree not because we knew other person was wrong, but we disagreed beacsue we were looking at things differently in scientific terms. And interms of asthetics i felt like we both had different expectations from what we wanted to achieve, which lead us to have different understanding of progress and in that sense we dont feel either of us is right or wrong, but it does influence the goal we want to achieve and how to form consensus over it?)

