### Dominic 


:::: {layout="[60,40]"}
::: {}
0) Title
1) Abstract
2) Introduction
:::
Write these last, find out what the report becomes. Then write Introduction etc
::::
3) Description of our thoughts & work; main source: our notes
4) reflection on the work
5) conclusion 


**Starting with 3):**

- our background, because this greatly affects how we could come to conclusions:

Our backgrounds of us as individuals clearly affects effects our understanding. Our interests as physicists would give rise to the starting point from where two interests need to be merged and agreed to the point to work on the same problem. 
On the other hand, our language background is defines our boundary conditions.
To agree upon the same problem the problem needs to be defined. This was done by defining the concepts like "semiconductor". 
The definition is given in relation to common words and technical words, which when defined are related to other common words and technical words and so on and so forth. In the end one creates a web of relations that define technical terms through this relation in terms of common words. Common words being those, that seem natural and need no further explanation in example:

**semiconductor**
: A material that can be tuned (i.e. Voltage $V$) to switch between two macroscopic behaviors: isolator & conductor 

Common words here could arguably be "material", "switch" or "behaviors". Of course this can be maybe avoided, by defining these terms as well, though there are two issues. One, the practicality under time constraints wanting whilst wanting to learn physics. Secondly the question about the actual possibility of clearly defining, without the use of technical terms, that need no definition which we, the authors, do not believe is possible (investigation of this would be interesting).

The two of us have a similar interest in physics. We studied similar courses with interests in the abstract mathematical concepts. "D" grew up in germany with bilingual english/german upbringing. "A" ...


- a description of our work throughout the two weeks

We, two people "A" and "D", were provided with an atomic physics experiment which allows students to perform the an experiment called "electromagnetically induced transparency". 
Within this framework the question that we must face is "What is it that we want to understand?"
Before we could tackle the task together, we needed a platform that allowed for independant working and thinking and also to unify our thoughts.
The platform we chose was github.
As a new working environment it took some time and effort to get used to the environment:

- planning of repository structure
- basic workflow
- functionality of branches 
- merging and merge conflicts

We decided for the following structure of the repository:

```
data/
  orientation.json 
figures/
notes/
  pictures/
  sections/
  lab_notes.qmd
  awais.qmd
  dominic.qmd
report/
```

With the goal of to have a structure to allow for constructive collaboration of two people. 
The "data" directory is a location for all data, with "orientation.json" capable for keeping track of the potential filenames (as keys) and the metadata. The notes contain the lab notes.
With a folder for pictures and sub sections that can be included. The two files "awais.qmd" and "dominic.qmd" were for preventing merge conflicts and independant working files, with the idea of concluding and merging our common knowladge in "lab_notes.qmd". This proofed difficult as the following paragraphs will give insights to.

The first problem we encounter is the question: What do we want to study? We went about this topic by first looking at the components of our experiment: 

- laser physics: external-cavity diode-laser (ECDL)
- atomic physics: $^{87}\text{Rn}(I=3/2)$, $^{85}\text{Rn}(I=5/2)$
- optics: alignment and optical components
    - linear polarizer
    - quarter wave plate
    - half wave plate
    - lense
    - Fabry-Pérot interferometer
- spectroscopy techniques: Absorption, Flourescence, and Saturation
- interferometery: Fabry-Pérot interferometer

From these aspects that we identified and thoroughly discussed what our interests were. We "decided upon" the detailed study of the "external-cavity diode-laser". It was the goal to get an in depth understanding so that we could eventually setup a numerical simulation of the ECDL. The process of deciding was based on:

- a discussion on each of the parts 
- argumentation of us describing our individual interests
- a written document that summerized the discussion concluded our decision

After deciding upon a topic we had to learn about the DLpro, the laser available to us and about the modeling of laser diodes.
Whilst "D" focused on gathering the information of the laser "Dlpro" @diode_manual, "A" focused on the the theoretical modeling of the diode. Throughout this phase we communicated our progress loosely, though we did not make it concrete. We took notes and also followed the advice of keeping a glossary in our respective files - seperately. Defining "important" concepts as well as variables.

The study of @diode_manual was motivated by the study of the input parameters and the output parameters:

**Input:**

- high speed frequency modulation port (-> frequency looking)
- current $I_{pd}$ 
- temperature $T_{pd}$
- Littrow grating angle $\alpha_g$
- grating constant $d$
- piezo actuator $V_{pz}$ -> external cavity $L$ & grating profile $\alpha_g$


**Output:**

- coherence length $>100\text{m}$
- line width $<1\text{MHz}$
- tuning to "several 10's of $\text{nm}$ without realignment" 
- tuning of 10's of $\text{GHz}$
- elliptical beam crosssecton (3:1)
  - "amorphic prism pair" can  reshape the cross-section
- collimated beam
- power/luminosity $P$ ($<500\text{mW}$)
- spectral distribution $\rho(\lambda)$
- free spectral range $\Delta \lambda$

Though the progress got sidetracked frequently. The idea of creating a numerical simulation for future students became attractive. This resulted in a change observable within the notes, as details on "how to use the DLpro" or "Tuning of the Diode Laser" were gathered, in hope to be helpful to others in the future. Though "important" notes as graphs by the manufacturer, capturing the input and output parameters were collected. The idea was, that the numerical simulation should be able to reproduce those, if modeled correctly. 
