### Introduction

Goal of the two weeks period was shifted from usual goals of being performative in experiments to learning the process of scientific research, (which not only includes progress and decisive steps but also consensus over steps and mutual understanding of progress), hence whole activity was focused on learning research process and we used topic of ECDL as more of direction for our two weeks.

- The task that we were given was to assign ourself a task and observe ourselves and find issues that we had in the process to achieving our goal.
- The goal we assigned ourselves was to try to understand a cavity diode laser and simulate a simple model of it.
- Aim was to keep track of how we progress and how do we live through the differences and process of coming to consencus. This will lead us to find a way to level our understanding and bridge gaps we both have and how to check if we both mean the same thing when we are talking about any scientific term or process.

### Description 


#### Git repo structure

We, two people "A" and "D", were provided with an atomic physics experiment which allows students to perform the an experiment called "electromagnetically induced transparency". 
Within this framework the question that we must face is "What is it that we want to understand?"
Before we could tackle the task together, we needed a platform that allowed for independant working and thinking and also to unify our thoughts.
The platform we chose was github.
As a new working environment it took some time and effort to get used to the environment:

- planning of repository structure
- basic workflow
- functionality of branches 
- merging and merge conflicts

We decided for the following structure of the repository:

```
data/
  orientation.json 
figures/
notes/
  pictures/
  sections/
  lab_notes.qmd
  awais.qmd
  dominic.qmd
report/
```

With the goal of to have a structure to allow for constructive collaboration of two people. 
The "data" directory is a location for all data, with "orientation.json" capable for keeping track of the potential filenames (as keys) and the metadata. The notes contain the lab notes.
With a folder for pictures and sub sections that can be included. The two files "awais.qmd" and "dominic.qmd" were for preventing merge conflicts and independant working files, with the idea of concluding and merging our common knowladge in "lab_notes.qmd". This proofed difficult as the following paragraphs will give insights to.


#### Finding a topic
The first problem we encounter was what we want to study? We went about this, by looking at the components of our experiment: 

- laser physics: external-cavity diode-laser (ECDL)
- atomic physics: $^{87}\text{Rn}(I=3/2)$, $^{85}\text{Rn}(I=5/2)$
- optics: alignment and optical components
    - linear polarizer
    - quarter wave plate
    - half wave plate
    - lense
    - Fabry-Pérot interferometer
- spectroscopy techniques: Absorption, Flourescence, and Saturation
- interferometery: Fabry-Pérot interferometer

From these topics we identified our interests. During the discussion we identified that the underlying tool for our experiment is the external-cavity diode-laser (ECDL). A consensus was reached to study the external-cavity diode-laser in detail. It was the goal to get an in depth understanding of our device, and be able to manipulate the laser through controllable parameters. This led us to try to simulate a model of the ECDL. This process of deciding was finalized with a written document, that summarized our thoughts and discussions as well as concrete next steps.

Though some issues that highlight the recursive manner of scientific work were still unsettled: Other fundamental tool for experimental obervation were power meter and interferometer that would be used to characterize the ECDL. Therefore require a thorough understanding, simultaneous to the understanding of the ECDL. 

"We find it difficult to pin our interests onto one specific topic. We would like to set up an experiment capable of observing the atomic structure, i.e. to see the fine structure– or hyperfine structure splitting. To set up an experiment that is capable of measuring these incredibly detailed measurements of physical structures we need to focus on the tools that we use to analyse the atomic structure of Rubidium.

In our opinion, to make the extremely detailed measurement of a atomic structure, a detailed understanding of the external-cavity diode-laser (ECDL) and its emission spectrum is required. Detailed knowledge on the diode laser should provide us with the means to setup a ideal frequency to observe the fine–, hyperfine structure. But how do we characterize the light of the ECDL? 

This brings us to the issue on spectroscopy. The Fabry-Pérot interferometer only measures relative spectra – though very precisely. To correctly characterize the emitted light of the ECDL, it seems advantageous to gain a deep understanding and a characterization of the Fabry-Pérot interferometer, which allows for the full characterization of the diode laser. The characterization of the ECDL go hand-in-hand with the characterization of the Fabry-Pérot interferometer.

The last point to be considered is optics. Not all optical components need to be understood in great detail to characterize the ECDL, though some shall be essential, i.e. a lense as well as the diffraction grating on a mirror are an integral part of the ECDL.

The set goal should be to **fully characterize the ECDL**, which by necessity shall include the characterization of other parts to the setup of the experimental set up to EIT.
This means, we want to:

- compare emission spectrum of ECDL with theoretical prediction of semiconductor physics:
  - How does the population inversion take place?
  - What is our semi conductor made of (i.e. GaAs)?
  - Is a characterization of the semi-conductor possible ($I–U$)?
  - What instruments do we have to measure the spectrum?
  - What is the Free spectral range of the ECDL (Fabry-Pérot modes)?
  - Temperature dependance of emitted spectrum?
  - Can we determine the diffraction index $n$ of the depletion region (optical fiber)

As concrete next steps, we need to find out about material compositions and the dimensions of the diode to then understand the models that describe the emission spectrum to make numerical predictions."

When delving into the literature, we realized that some of the task we set ourselves, could not be achieved. It appeared, that the parameters and dimension of the diode, that were expected to be easily obtained were not given in the handbook. 

Retrospectively it would require to document this observation and to redefine our task. Though we felt the urge to continue the literature research. This issue will become apparent in the following section.


#### Literature
During our first week, first problem we dealt with was finding literature relevant to what we wanted to achieve. This made us come decide to explore literature independently. Our plan was to later discuss what we have read and bridge knowledge gaps between the two of us. Then come to a conclusion on how to proceed.

We focused on literature around diode laser in general and particularly about DLpro the laser available to us and about the characterization of laser diodes.
Throughout this phase we communicated our progress loosely. We took notes and also followed the advice of keeping a glossary in our respective files - separately. Defining "important" concepts as well as variables.

This separation of work, of loosely communicating our struggles, resulted in deviating from our task rather than focusing on a clear goal.  
After reading different literature we still had issues communicating the information and bridging the gap to come to a consensus about our next step.


Finding "relevant" or "good" literature to read is something we struggled with. Searching for literature over internet is tricky, as much as we have a lot of information it also results in deviation from original task. 
The task we set ourselves does not perfectly match the literature we come across first. Then when starting to read, we found ourselves delving deeply into one specific topic. This conflicts with trying to obtain a broad understanding of our topic. As to reach our set goal.

After our literature review we tried to simulate a basic model (with help of AI), and we kept track of the parameter of our interest. After simulating a simple model, we realized that the geometric parameter of our interest i.e.: cavity-length was not available to us. The simulation also made us realize that the information and our understanding that we obtained only reveals a limited instight. The real device fluctuates, though model did not. Which lead to the question how to model the errors and fluctuations. This lead us to the conclusion to take experimental data from our laser DLpro.

#### Second Week Direction

Try to have numerical model of these parameter and play around with the inputs and observe dynamics of output and understand the behaviour, and in mean while take data of inputs from real experimental setup and observe if our understanding of dynamics make sense or not, and what
pieces of puzzle are we missing.


##### Experimental Attempt

We started our experiment by taking data of intensity power (with use of photodiode), by varying the current, the other measureable parameter was peizo current (which is related to length of cavity). During our experient and tracking data we realized that the peizo voltage was not stable, it was fluctuating and drifting, leading to change in threshold current, and change in central mode. which made us realize that our output was influenced by two parameters. This lead us to have discussion and question our understanding of our ECDL setup. few of the points we wanted to revist were, how external cavity is affected if we turn peizo off, would it favour us?, would it be better to find optimal hopfree mode?, and what should be our next step, and what do we want to achieve?



### Issues
>"In the time when we don't set anything as definite truth, all statements are equal truths"

Our two weeks journey was never short of difficulties. This made us realize how the scientific process itself could be difficult. Among all other major and minor issues, a prominent one is the drive or motivation to always be optimistic every day.

One of core issue we can pinpoint is finding structure to our progress in the time of disagreement.

Another important issue was communication: how to express thoughts in the best possible way, how to make sure that information was transferred clearly and without too much deviation, and how to know whether we had reached the same understanding. This also raised the question of how we come to agreement when our interpretations are not exactly the same.

Throughout the entire process, a reoccuring conflict that we observed and tried to understand were our expectations as individuals. However, what exactly these differences were, and where they came from, was not easy to identify. So far, we could formulate them through two statements. On the one hand: “I feel like I am free, so I want to make the most out of this opportunity.” On the other hand: “I felt like, as there are no expectations, I would just want to enjoy the process of learning without really worrying about doing a lot.” This made us question how we could find a middle ground in terms of our expectations. 

Our differences were not only scientific but also aesthetic in nature. At times, our disagreementwere not about right or wrong, but because different prespectives. In terms of aesthetics, we felt that we both had different preferences which expressed itself in our expectations of progress, and also was visible in glossary section while coming to consencus about definitions. In that sense, we did not feel that either of us was right or wrong, but these differences still influenced the goal we wanted to achieve and how we could form consensus over it.

More importantly, this made us question how these expectations reflected in our struggle to work scientifically together, and what we could do to overcome this.

The issue of time connected back to the larger difficulty of maintaining motivation and optimism throughout the process. This became especially clear toward the end, when progress, in the sense of advancing, seeing quick results, or having something to present to a third person, was not reached. Having little time left for any further work led us to stutter and come to a halt. At that point, simple philosophical questions made us question the most basic thing: what are we doing here, and why are we doing what we were doing?

### Reflection

Our backgrounds of us as individuals clearly affects effects our understanding. Our interests as physicists would give rise to the starting point from where two interests need to be merged and agreed to the point to work on the same problem. 
On the other hand, our language background is defines our boundary conditions.
To agree upon the same problem the problem needs to be defined. This was done by defining the concepts like "semiconductor". 
The definition is given in relation to common words and technical words, which when defined are related to other common words and technical words and so on and so forth. In the end one creates a web of relations that define technical terms through this relation in terms of common words. Common words being those, that seem natural and need no further explanation in example:

**semiconductor**
: A material that can be tuned (i.e. Voltage $V$) to switch between two macroscopic behaviors: isolator & conductor 

Common words here could arguably be "material", "switch" or "behaviors". Of course this can be maybe avoided, by defining these terms as well, though there are two issues. One, the practicality under time constraints wanting whilst wanting to learn physics. Secondly the question about the actual possibility of clearly defining, without the use of technical terms, that need no definition which we, the authors, do not believe is possible (investigation of this would be interesting).

The two of us have a similar interest in physics. We studied similar courses with interests in the abstract mathematical concepts. "D" grew up in germany with bilingual english/german upbringing. "A" ...

(We should add in the following that our "progress" or our mind was on the questions of expectation. We were confused by the change of structure. Sure UW told us there are no expectations, but we were not sure. So the impression we had the about activity was learning about learning, which sounds introspective. One is introspective toward the past, not the present. Trying to be introspective made us more conflicted or unsure about what do next, and how to asses ourselves while doing it.)

Especially in time constrained working environment does not allow to deviate much.

- Feeling of not being able to completely be confident in knowledge was always there.

Though the progress got sidetracked frequently. The idea of creating a numerical simulation for future students became attractive. This resulted in a change observable within the notes, as details on "how to use the DLpro" or "Tuning of the Diode Laser" were gathered, in hope to be helpful to others in the future. Though "important" notes as graphs by the manufacturer, capturing the input and output parameters were collected. The idea was, that the numerical simulation should be able to reproduce those, if modeled correctly. 

#### Consensus in Scientific work

Consensus on Wikipedia is defined as a general agreement, accord, or harmony in opinion or attitude among a group.

Consensus itself is one of the intrinsic features in scientific work; during our two weeks of EIT experiment, we spent time pondering that question of consensus and also about how to agree when we are not dictated to by right or wrong by a supervisor (because in this two-week period we were given total freedom, which means there were no expectations to hold up either. This reminds me of a statement by Kafka: 'I am free, and that is why I am lost.' Which was how we felt for most of two weeks.

We both agreed that in order to make scientific progress, one needs a system of active input and a feedback loop. (We defined progress as active agreement between person "A" and "D", not progress in a performative sense.)

**(We need to define our system of active input and a feedback loop)**: This system is kind of underlying; without actively working on it, **input** is we first try to define (one needs to explain what it means to say we define something) one thing as we understand it, and the person starts to ask questions around their doubts about how we have defined the thing. Which I consider **feedback**.

This is more of a reflection on our two weeks and suggestions on how this could have been better and could be followed for our future endeavours.




### Conclusion
- The most valuable skill one can ever learn is ability to figure it out

- One way to make proper progress is to have two set of notes, one with unordered thoughts and explaination, and then develope on it into seperate notes which are more organized, and structured.(it is very retrospective way to take notes) 